---
- name: "Nginx | Create certbot challenge directory"
  file:
    path: /var/www/certbot
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Check if SSL certificates exist"
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: ssl_cert_file
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Set SSL certificate status"
  set_fact:
    ssl_cert_exists: "{{ ssl_cert_file.stat.exists | default(false) }}"
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Generate Nginx configuration"
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ domain_name }}"
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Enable site"
  file:
    src: "/etc/nginx/sites-available/{{ domain_name }}"
    dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
    state: link
  notify: reload nginx
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Remove default site"
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Test Nginx configuration"
  shell: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  tags:
    - nginx
    - reverse_proxy
    - test

- name: "Nginx | Enable Nginx service"
  systemd:
    name: nginx
    enabled: yes
    state: started
  tags:
    - nginx
    - reverse_proxy

- name: "Nginx | Flush handlers"
  meta: flush_handlers
  tags:
    - nginx
